#插件基本信息
pluginGroup=com.ke
pluginName=CodeLink
pluginVersion=0.1.0

ideType:idea
# ideType:pycharm
# ideType:goland
# ideType:phpstorm
# ideType:webstorm



phpStormVersion:2024.1.1
webStormVersion:2024.1.1
ideGoVersion:2024.1
idePycharmVersion:2024.1
intellijBuildVersion=2023.1
#intellijBuildVersion=2024.1
#intellijBuildVersion=2024.2
#intellijBuildVersion=2025.1